[params]
BookFavicon = "logo.png"

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "archetypes"
target = "archetypes"